name: gsheet_to_arb_example
description: Example of how to use ghseet_to_arb plugin

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  intl: ^0.19.0

dev_dependencies:
  gsheet_to_arb:
    path: '../'
