name: gsheet_to_arb_example
description: Example of how to use ghseet_to_arb plugin

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  gsheet_to_arb:
    path: ../

gsheet_to_arb: 
  arb_file_prefix: "lib/src/i18n"
  localization_file_name: "S"
  output_directory: "intl"
  gsheet: 
    auth_file: "./gsheet_to_arb.yaml"
    category_prefix: "# "
    document_id: "TODO"
    sheet_id: "0"
