name: gsheet_to_arb_example
description: Example of how to use ghseet_to_arb plugin

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  gsheet_to_arb:
    path: ../

gsheet_to_arb:
  arb_file_prefix: 'intl'
  output_directory: 'lib/src/i18n'
  gsheet:
    document_id: '1CwFRjtiCmCl8yvP55yBT70h-Yt00CcigD816hsGo7KU'
    sheet_id: '0'
    auth:
      auth_file: "gsheet_to_arb.yaml"