name: gsheet_to_arb
version: 0.1.11
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  args: ^2.3.1
  dart_style: ^2.2.3
  intl: ^0.19.0
  path: ^1.8.2
  googleapis_auth: ^1.3.1
  googleapis: ^13.1.0
  code_builder: ^4.2.0
  json_annotation: ^4.6.0
  logging: ^1.0.2
  recase: ^4.0.0
  quiver: ^3.1.0
  yaml: ^3.1.1
  petitparser: ^6.0.2
  uuid:
  # file_utils:

dev_dependencies:
  analyzer: ^6.5.0
  test: ^1.21.4
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
