name: gsheet_to_arb
version: 0.0.2+1
author: Marcin Marek Gocał <marcin.gocal@gmail.com>
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.33.0-alpha.0 <0.34.0'
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  intl: '>=0.15.3 <0.16.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=1.1.3 < 3.0.0'
  googleapis_auth: ^0.2.6
  googleapis: ^0.52.0+1
  code_builder: ^3.1.3
  built_value: ^6.1.6
dev_dependencies:
  test: ^1.2.0