name: gsheet_to_arb
version: 0.1.11
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  args: ^2.3.1
  dart_style: ^2.2.3
  intl: ^0.17.0
  path: ^1.8.2
  googleapis_auth: ^1.3.1
  googleapis: ^9.1.0
  code_builder: ^4.2.0
  intl_translation:
    git: 
      url: https://github.com/agniswarmandal/intl_translation.git
      ref: master
  json_annotation: ^4.6.0
  file_utils: ^1.0.1
  logging: ^1.0.2
  recase: ^4.0.0
  quiver: ^3.1.0
  yaml: ^3.1.1
  petitparser: ^5.0.0

dev_dependencies:
  analyzer: ^4.3.1
  test: ^1.21.4
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  pedantic: ^1.11.1
